// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmixtqmutvryppcgqvys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaXh0cW11dHZyeXBwY2dxdnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTQ1NTcsImV4cCI6MjA1NjY5MDU1N30.6rMOpKpKvqEYEU4CuVbAjhbo3APW_B5FwHhLEDOpBiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);